import { NextRequest, NextResponse } from "next/server";
import { writeFile } from "fs/promises";
import { join } from "path";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const session = req.cookies.get("admin_session")?.value;
  if (session !== process.env.ADMIN_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { plans } = await req.json() as {
    plans: Array<{ days: number; label: string; price: number }>;
  };

  if (!plans || !Array.isArray(plans)) {
    return NextResponse.json({ error: "Invalid plans" }, { status: 400 });
  }

  // Validate no price drops
  for (let i = 1; i < plans.length; i++) {
    if (plans[i].price < plans[i - 1].price) {
      return NextResponse.json({
        error: `מחיר של "${plans[i].label}" (₪${plans[i].price/100}) נמוך מ"${plans[i-1].label}" (₪${plans[i-1].price/100})`,
      }, { status: 400 });
    }
  }

  const content = `// Auto-generated by admin pricing editor
// Last updated: ${new Date().toISOString()}
export const PLANS = [
${plans.map((p) =>
  `  { days: ${p.days},  label: "${p.label}",  price: ${p.price} },  // ₪${Math.round(p.price/100)}`
).join("\n")}
] as const;

export type Plan = (typeof PLANS)[number];
export type PlanDays = Plan["days"];

export function getPlanByIndex(index: number): Plan {
  return PLANS[Math.max(0, Math.min(index, PLANS.length - 1))];
}

export function getPlanCount(): number {
  return PLANS.length;
}

export function getPriceForMonths(months: number): number {
  const days = Math.round(months * 30);
  return [...PLANS].sort((a, b) =>
    Math.abs(a.days - days) - Math.abs(b.days - days)
  )[0].price;
}

export function getPricePerMonth(months: number): number {
  return Math.round(getPriceForMonths(months) / months);
}
`;

  const filePath = join(process.cwd(), "lib", "plans.ts");
  await writeFile(filePath, content, "utf-8");

  return NextResponse.json({ ok: true });
}
